version: '3.4'

services:
  dinosauruspark:
    image: dinosauruspark
    build:
      context: .
      dockerfile: src/DinosaurusPark/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DINOPARK_DB__CONNECTIONSTRING: Host=pg;Port=5432;Database=dinosaurus_park;Username=postgres;
    depends_on:
      - pg
    ports:
      - "5000:80"

  pg:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./10-init-pg.sql:/docker-entrypoint-initdb.d/10-init-pg.sql
volumes:
  pgdata: