version: '3.4'

services:
  dinosauruspark.web:
    image: dinosauruspark.web
    build:
      context: .
      dockerfile: src/DinosaursPark.WebApplication/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DINOPARK_DB__CONNECTIONSTRING: Host=pg;Port=5432;Database=dinosaurus_park;Username=postgres;
      DINOPARK_SERILOG__SystemLogsLevel: Debug
      DINOPARK_SERILOG__MicrosoftLogsLevel: Warning
      DINOPARK_SERILOG__CustomLogsLevel: Debug
      DINOPARK_SERILOG__USEREQUESTLOGGING: "true"
      DINOPARK_FILES__ROOT: wwwroot/img/dinosaurs
      DINOPARK_FILES__SHORTROOT: /img/dinosaurs
    depends_on:
      - pg
    ports:
      - "5005:80"

  pg:
    image: postgres:10.11
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: